[package]
name = "domingler"
version = "0.2.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]
edition = "2018"

[dependencies]
anyhow = "~1.0.34"
regex = "~1.4.2"
lazy_static = "~1.4.0"
maplit = "~1.0.2"
nom = "~6.0.1"
either = "~1.6.1"
