[package]
name = "domingler"
version = "0.1.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]
edition = "2018"

[dependencies]
regex = "~1.1.7"
lazy_static = "~1.3.0"
maplit = "~1.0.1"
nom = "~5.0.1"
either = "~1.5.2"
